package cz.osu.project_todoholecekp_hrtonm.Model;

public enum SortingType {
    CATEGORY_TITLE_ASC, CATEGORY_TITLE_DESC, CATEGORY_TASKS_COUNT_ASC, CATEGORY_TASKS_COUNT_DESC,
    TASK_TITLE_ASC, TASK_TITLE_DESC, TASK_DEADLINE_ASC, TASK_DEADLINE_DESC, TASK_COMPLETED_ASC, TASK_COMPLETED_DESC
}
